# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SJProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SJProject
  pod 'AFNetworking', '~> 3.0'

  target 'SJProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SJProjectUITests' do
    # Pods for testing
  end

end
